# .gitpod.yml for Flutter project
image: gitpod/workspace-full:latest

tasks:
  - name: Setup Flutter
    init: |
      # The gitpod/workspace-full image should have most tools, but we ensure Flutter is on path.
      # A common issue is the Flutter SDK not being on the PATH.
      # We will rely on the image having Flutter and just run the necessary commands.
      echo "Setting up Flutter environment..."
      flutter doctor -v
      flutter pub get
    command: |
      echo "Starting Flutter web application..."
      flutter run -d web --web-hostname 0.0.0.0 --web-port 8080

ports:
  - port: 8080
    onOpen: open-browser
    name: Flutter Web App
